const todosActionTypes = {
  ADD_OUTER_TODOS: "ADD_OUTER_TODOS",
  ADD_INNER_TODO: "ADD_INNER_TODO",
  DELETE_INNER_TODO: "DELETE_INNER_TODO",
  UPDATE_INNER_TODO: "UPDATE_INNER_TODO",
  DATE_INCREMENT: "DATE_INCREMENT",
  DATE_DECREMENT: "DATE_DECREMENT",
  FETCHING_TODOS: "FETCHING_TODOS",
  ERROR_FETCHING: "ERROR_FETCHING",
};

export default todosActionTypes;
