const todosActionTypes = {
  ADD_OUTER_TODOS: "ADD_OUTER_TODOS",
  ADD_INNER_TODO: "ADD_INNER_TODO",
  DELETE_INNER_TODO: "DELETE_INNER_TODO",
  UPDATE_INNER_TODO: "UPDATE_INNER_TODO",
};

export default todosActionTypes;
