const todosActionTypes = {
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  FETCH_TODOS: "FETCH_TODOS",
  LOADING_TODOS: "LOADING_TODOS",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  CLEAR_TODO_LIST: "CLEAR_TODO_LIST",
};

export default todosActionTypes;
